### ISSUE TITLE
Deployment to now

### ISSUE THREAD

**Issue by surepe** [madeagency/reactivity#7]
Hey, thanks for this future tech. 

I am getting this under deployment to zeit/now: 

```javascript
> /home/nowuser/src/bin/server.js:40
>     const clientStats = stats.toJson().children[0]
>                              ^
> TypeError: Cannot read property 'toJson' of undefined
```

**Comment by rocbear** [comment]
Hi @surepe, thanks for checking out Reactivity!

It would help if you could give the steps you followed to get this error. Did you use a`now.json` for configuration, and specify environment variables?

**Comment by surepe** [comment]
I've revert my changes to project and this is the result of deploying an untouched reactivity. Seems like we can't do another webpack manipulations on "start".

```
> ▲ npm start
> > reactivity@0.1.0 start /home/nowuser/src
> > node bin/server.js
> Error: EACCES: permission denied, open 'buildServer/main.js'
>     at Object.fs.openSync (fs.js:652:18)
>     at Object.fs.writeFileSync (fs.js:1299:33)
```

Anyway, it's gotta be cool if you have some time and provide working deployment setup to zeit/now. 

Thanks!

**Comment by dawidvdh** [comment]
Hey @surepe we have resolved your issue, please pull the latest changes and when deploying with `now` you need to provide the `.env` file using `-E FILE, --dotenv=FILE` like so `now --dotenv=.env`.

**Comment by rocbear** [comment]
Great work @dawidvdh. `--dotenv` looks for `.env` by default so `now --dotenv` should do the trick too if you've copied `.sample.env` to `.env`
